import{shuffle,clone,other,legalPlay,legalAttack,attackTargets,winner}from'./rule-engine.js';import{resolveEffects}from'./effect-engine.js?v=3440';import{chooseDefense}from'./ai-engine.js?v=3440';let uid=0;const inst=c=>({...clone(c),uid:`c${++uid}`,rested:false,summoningSickness:false,attachedDon:0,tempPower:0});
export class GameEngine{
constructor(cards,decks){this.cards=cards;this.decks=decks;this.history=[]}buildSide(side,d){return{side,leader:inst(this.cards[d.leader]),deck:shuffle(d.cards.flatMap(x=>Array.from({length:x.count},()=>inst(this.cards[x.id])))),hand:[],life:[],field:[],trash:[],don:{total:0,active:0,rested:0},mulliganDone:false,defeated:false}}
start(first='player'){this.history=[];this.state={version:2,turn:0,activeSide:first,firstPlayer:first,phase:'mulligan',winner:null,pending:null,log:[],sides:{player:this.buildSide('player',this.decks.player),ai:this.buildSide('ai',this.decks.ai)}};for(const k of['player','ai']){this.draw(k,5,false);const s=this.state.sides[k];for(let i=0;i<s.leader.life;i++)s.life.push(s.deck.pop())}this.log('対戦準備完了。初手を確認してください。');return this.state}
snapshot(){this.history.push(clone(this.state));if(this.history.length>80)this.history.shift()}undo(){if(!this.history.length)return false;this.state=this.history.pop();this.log('1手戻しました');return true}log(text){this.state.log.push({at:Date.now(),text});if(this.state.log.length>120)this.state.log.shift()}
draw(side,n=1,snap=true){if(snap)this.snapshot();const s=this.state.sides[side];for(let i=0;i<n;i++){if(!s.deck.length){s.defeated=true;break}s.hand.push(s.deck.pop())}return this.checkWin()}
mulligan(side,keep){this.snapshot();const s=this.state.sides[side];if(!keep){s.deck=shuffle([...s.deck,...s.hand]);s.hand=[];for(let i=0;i<5;i++)s.hand.push(s.deck.pop());this.log('あなたがマリガンしました')}else this.log('あなたが初手をキープしました');s.mulliganDone=true;this.state.sides.ai.mulliganDone=true;this.log('AIが初手をキープしました');this.beginTurn()}
beginTurn(){const side=this.state.activeSide,s=this.state.sides[side];this.state.turn++;s.leader.rested=false;s.leader.attachedDon=0;for(const c of s.field){c.rested=false;c.summoningSickness=false;c.attachedDon=0;c.tempPower=0}s.don.active=s.don.total;if(this.state.turn>1)this.draw(side,1,false);const add=this.state.turn===1&&side===this.state.firstPlayer?1:Math.min(2,10-s.don.total);s.don.total+=add;s.don.active+=add;this.state.phase='main';this.log(`${this.state.turn}ターン目：${side==='player'?'あなた':'AI'}のメインフェーズ`)}
async playCard(side,id){const s=this.state.sides[side],c=s.hand.find(x=>x.uid===id);if(!c||!legalPlay(this.state,side,c))return false;this.snapshot();s.don.active-=c.cost;s.don.rested+=c.cost;s.hand=s.hand.filter(x=>x.uid!==id);if(c.type==='character'){c.summoningSickness=true;s.field.push(c);this.log(`${c.name}を登場`)}else{this.log(`${c.name}を使用`)}await resolveEffects({engine:this,state:this.state,side},'onPlay',c);if(c.type==='event')s.trash.push(c);return true}
attachDon(side,id,amount=1){const s=this.state.sides[side],c=[s.leader,...s.field].find(x=>x.uid===id),n=Math.min(amount,s.don.active);if(!c||n<1||this.state.activeSide!==side||this.state.phase!=='main')return false;this.snapshot();s.don.active-=n;s.don.rested+=n;c.attachedDon=(c.attachedDon||0)+n;this.log(`${c.name}にDON!!を${n}枚付与`);return true}
async declareAttack(side,aid,tid){const s=this.state.sides[side],a=[s.leader,...s.field].find(x=>x.uid===aid);if(!a||!legalAttack(this.state,side,a))return false;const t=attackTargets(this.state,side).find(x=>x.uid===tid);if(!t)return false;this.snapshot();a.rested=true;const foe=this.state.sides[other(side)],tc=t.kind==='leader'?foe.leader:foe.field.find(x=>x.uid===tid);this.state.pending={attackingSide:side,defendingSide:other(side),attackerUid:aid,targetUid:tid,targetKind:t.kind,power:a.power+(a.attachedDon||0)*1000+(a.tempPower||0),targetPower:tc.power+(tc.tempPower||0),counterPower:0};this.log(`${a.name}が${t.name}へ${this.state.pending.power}で攻撃`);await resolveEffects({engine:this,state:this.state,side},'onAttack',a);return true}
defend(side,{blockerUid=null,counters=[]}={}){const a=this.state.pending;if(!a||a.defendingSide!==side)return false;this.snapshot();const s=this.state.sides[side];if(blockerUid){const b=s.field.find(c=>c.uid===blockerUid&&!c.rested&&(c.keywords||[]).includes('blocker'));if(b){b.rested=true;a.targetUid=b.uid;a.targetKind='character';a.targetPower=b.power;this.log(`${b.name}でブロック`)}}for(const id of counters){const c=s.hand.find(x=>x.uid===id);if(c?.counter){a.counterPower+=c.counter;s.hand=s.hand.filter(x=>x.uid!==id);s.trash.push(c);this.log(`${c.name}をカウンターに使用`)}}return this.resolveAttack()}
autoResolveDefense(){const a=this.state.pending;if(a)return this.defend(a.defendingSide,chooseDefense(this.state,a.defendingSide,a))}resolveAttack(){const a=this.state.pending,s=this.state.sides[a.defendingSide],hit=a.power>=a.targetPower+a.counterPower;if(hit&&a.targetKind==='leader'){if(s.life.length){s.hand.push(s.life.pop());this.log('ライフを1枚手札へ')}else{s.defeated=true;this.log('勝敗が決まりました')}}else if(hit){const c=s.field.find(x=>x.uid===a.targetUid);if(c){s.field=s.field.filter(x=>x.uid!==c.uid);s.trash.push(c);this.log(`${c.name}をKO`)}}else this.log('アタックを守りました');this.state.pending=null;return this.checkWin()}
zoneCards(side,zone){const s=this.state.sides[side];return zone==='field'?s.field:(s[zone]||[])}
manualMove(side,from,to,id){const s=this.state.sides[side],source=this.zoneCards(side,from),index=source.findIndex(c=>c.uid===id);if(index<0)return false;this.snapshot();const[card]=source.splice(index,1);card.rested=false;card.attachedDon=0;card.tempPower=0;if(to==='deckTop')s.deck.push(card);else if(to==='deckBottom')s.deck.unshift(card);else if(to==='lifeTop')s.life.push(card);else if(to==='lifeBottom')s.life.unshift(card);else if(to==='field'){card.summoningSickness=true;s.field.push(card)}else if(s[to])s[to].push(card);else return false;this.log(`${card.name}を${this.zoneName(to)}へ移動`);return true}
zoneName(zone){return({hand:'手札',trash:'トラッシュ',deckTop:'デッキ上',deckBottom:'デッキ下',lifeTop:'ライフ上',lifeBottom:'ライフ下',field:'場'}[zone]||zone)}
shuffleDeck(side){this.snapshot();this.state.sides[side].deck=shuffle(this.state.sides[side].deck);this.log(`${side==='player'?'自分':'AI'}のデッキをシャッフル`);return true}
async useTrigger(side,id){const s=this.state.sides[side],index=s.life.findIndex(c=>c.uid===id);if(index<0)return false;this.snapshot();const[card]=s.life.splice(index,1);const triggers=(card.effects||[]).filter(e=>e.timing==='trigger');if(triggers.length){this.log(`${card.name}のトリガーを使用`);await resolveEffects({engine:this,state:this.state,side},'trigger',card)}else this.log(`${card.name}には登録済みトリガーがありません`);s.trash.push(card);return true}
endTurn(side){if(this.state.activeSide!==side)return false;this.snapshot();this.log(`${side==='player'?'あなた':'AI'}がターン終了`);this.state.activeSide=other(side);this.beginTurn();return true}checkWin(){const w=winner(this.state);if(w){this.state.winner=w;this.state.phase='gameOver';this.log(`${w==='player'?'あなた':'AI'}の勝利`)}return w}export(){return clone(this.state)}load(s){const next=clone(s);next.version=2.2;next.pending??=null;next.log??=[];for(const side of['player','ai']){next.sides[side].trash??=[];for(const c of[next.sides[side].leader,...next.sides[side].field,...next.sides[side].hand]){c.attachedDon??=0;c.tempPower??=0}}this.state=next;this.history=[]}}
