const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null)node.setAttribute(key,value)}for(const child of children.flat())node.append(child?.nodeType?child:document.createTextNode(child??''));return node};
const cardButton=(card,onTap)=>el('button',{class:`card ${card.color?.[0]||''} ${card.type==='event'?'event':''} ${card.rested?'rested':''}`,onClick:()=>onTap(card)},el('span',{class:'card-name'},card.name),el('span',{class:'card-meta'},card.type==='event'?'EV':`C${card.cost??'-'}`,String(card.power||`+${card.counter||0}`)));
const life=count=>el('div',{class:'life'},...Array.from({length:count},()=>el('b')));
const don=pile=>el('div',{class:'don'},...Array.from({length:pile.total},(_,i)=>el('i',{class:i>=pile.active?'used':''})));
export class UI{
 constructor(root,actions){this.root=root;this.a=actions;this.modal=null}
 renderHome(hasSave){this.root.replaceChildren(el('section',{class:'screen hero'},el('div',{class:'brand'},'ONE PIECE CARD',el('small',{},'AI TRAINER Ver2.1')),el('h1',{},'黒黄ティーチ vs 紫エネル'),el('p',{},'スマホ向けAI対戦トレーナー'),el('div',{class:'versus'},el('div',{class:'deck-tile'},'PLAYER',el('strong',{},'黒黄ティーチ')),el('b',{},'VS'),el('div',{class:'deck-tile'},'AI',el('strong',{},'紫エネル'))),el('div',{class:'setup'},el('div',{class:'choice'},el('button',{onClick:()=>this.a.newGame('player')},'先攻で開始'),el('button',{class:'purple',onClick:()=>this.a.newGame('ai')},'後攻で開始')),hasSave?el('button',{onClick:this.a.load},'保存した対戦を続ける'):'')))}
 side(g,key,label){const s=g.sides[key];return el('section',{class:`side ${key}`},el('div',{class:'side-head'},el('div',{class:'identity'},cardButton(s.leader,c=>this.a.card(key,c)),el('div',{class:'stats'},el('strong',{},label),el('br'),`手札 ${s.hand.length} / 山札 ${s.deck.length}`)),life(s.life.length)),el('div',{class:'zone-label'},`DON!! ${s.don.active}/${s.don.total}`),don(s.don),el('div',{class:'zone-label'},'キャラクター'),el('div',{class:'cards'},...(s.field.length?s.field.map(c=>cardButton(c,x=>this.a.card(key,x))):[el('span',{class:'empty'},'キャラクターなし')])))}
 renderGame(g){const end=el('button',{class:'primary',onClick:this.a.endTurn},'ターン終了');end.disabled=g.activeSide!=='player'||g.phase!=='main'||Boolean(g.pending);const logs=g.log.slice(-5).reverse().map(x=>el('div',{},x.text));this.root.replaceChildren(el('div',{class:'shell'},el('header',{class:'topbar'},el('div',{class:'brand'},'OP AI TRAINER',el('small',{},'ENGINE Ver2.1')),el('div',{class:'chips'},el('span',{class:'chip'},g.activeSide==='player'?'あなたの番':'AIの番'),el('span',{class:'chip'},`T${g.turn}`))),el('div',{class:'board'},this.side(g,'ai','紫エネル AI'),el('section',{class:'center'},el('div',{},el('div',{class:'turn'},g.winner?`${g.winner==='player'?'あなた':'AI'}の勝利`:g.pending?'カウンターステップ':`${g.turn}ターン目`),el('div',{class:'phase'},g.phase)),el('div',{class:'log'},...logs)),this.side(g,'player','黒黄ティーチ')),el('div',{class:'hand-wrap'},el('section',{class:'hand'},el('div',{class:'zone-label'},`手札 ${g.sides.player.hand.length}枚`),el('div',{class:'cards'},...g.sides.player.hand.map(c=>cardButton(c,x=>this.a.card('player',x)))))),el('nav',{class:'toolbar'},el('button',{class:'ghost',onClick:this.a.home},'終了'),el('button',{onClick:this.a.undo},'↶ 戻す'),el('button',{onClick:this.a.save},'保存'),end)));if(g.phase==='mulligan')this.sheet('初手を確認','この5枚で始めますか？',[['キープ',()=>this.a.mulligan(true),'primary'],['マリガン',()=>this.a.mulligan(false),'']]);if(g.pending?.defendingSide==='player')this.defense(g)}
 showCard(side,c,g){const buttons=[];if(side==='player'&&g.activeSide==='player'&&g.phase==='main'){if(g.sides.player.hand.some(x=>x.uid===c.uid))buttons.push(['登場・使用',()=>this.a.play(c.uid),'primary']);else{if(g.sides.player.don.active>0)buttons.push(['DON!!を1枚付与',()=>this.a.attachDon(c.uid),'']);if(!c.rested)buttons.push(['攻撃する',()=>this.a.attack(c.uid),'primary'])}}buttons.push(['閉じる',()=>this.close(),'']);this.sheet(c.name,`コスト ${c.cost??'-'} / パワー ${c.power||'-'} / カウンター ${c.counter||0}\n付与DON!! ${c.attachedDon||0}枚\n${c.text||'効果未登録'}`,buttons)}
 targets(items){this.sheet('攻撃対象を選択','対象を選んでください。',items.map(x=>[x.name,()=>this.a.target(x.uid),x.kind==='leader'?'primary':'']))}
 defense(g){const a=g.pending,s=g.sides.player,counters=s.hand.filter(c=>c.counter>0),selected=new Set();const choices=counters.map(c=>[`カウンター ${c.counter}：${c.name}`,()=>{selected.add(c.uid);this.a.defend({counters:[...selected]})},'']);choices.push(['受ける',()=>this.a.defend({}),'primary']);this.sheet('防御を選択',`攻撃 ${a.power} / 対象パワー ${a.targetPower}`,choices)}
 sheet(title,text,buttons){this.close();this.modal=el('div',{class:'dialog'},el('section',{class:'sheet'},el('h2',{},title),el('p',{},text),el('div',{class:'actions'},...buttons.map(([label,fn,cls])=>el('button',{class:cls,onClick:fn},label)))));document.body.append(this.modal)}
 close(){this.modal?.remove();this.modal=null}toast(text){const note=el('div',{class:'toast'},text);document.body.append(note);setTimeout(()=>note.remove(),1500)}
}
