import{UI}from'./ui-fixed.js?v=3441';
const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null&&value!==undefined)node.setAttribute(key,value)}for(const child of children.flat())node.append(child?.nodeType?child:document.createTextNode(child??''));return node};
const battleCards=g=>{const battle=g.pending,attackSide=g.sides[battle.attackingSide],defenseSide=g.sides[battle.defendingSide],attacker=attackSide.leader.uid===battle.attackerUid?attackSide.leader:attackSide.field.find(card=>card.uid===battle.attackerUid),target=battle.targetKind==='leader'?defenseSide.leader:defenseSide.field.find(card=>card.uid===battle.targetUid);return{battle,attacker,target}};
const miniCard=(card,label,power)=>el('div',{class:'leader-battle-card'},el('span',{},label),card?.imageUrl?el('img',{src:card.imageUrl,alt:card.name}):el('div',{class:'leader-battle-fallback'},card?.name||'不明なカード'),el('strong',{},card?.name||'不明なカード'),el('b',{},String(power||0)));
const previousLeaderRedirect=UI.prototype.leaderRedirect;
UI.prototype.leaderRedirect=function(g){
 previousLeaderRedirect.call(this,g);const panel=this.modal?.querySelector('.redirect-flow');if(!panel)return;const{battle,attacker,target}=battleCards(g),decorate=()=>{const head=panel.querySelector('.redirect-head');if(!head||head.querySelector('.leader-attack-context'))return;head.append(el('div',{class:'leader-attack-context'},miniCard(attacker,'攻撃元',battle.power),el('div',{class:'leader-attack-arrow'},'→'),miniCard(target,'現在の対象',battle.targetPower)))};decorate();const observer=new MutationObserver(decorate);observer.observe(panel,{childList:true,subtree:true});panel.addEventListener('DOMNodeRemovedFromDocument',()=>observer.disconnect(),{once:true});
};
const previousCounterPrompt=UI.prototype.counterImagePrompt;
UI.prototype.counterImagePrompt=function(g){
 previousCounterPrompt.call(this,g);const footer=this.modal?.querySelector('.counter-visual-flow .redirect-footer');if(!footer)return;const side=g.sides.player,battle=g.pending,canReturn=battle?.kind==='battle'&&battle.defendingSide==='player'&&side.leader.id==='OP16-080'&&side.leaderRedirectTurn!==g.turn&&side.hand.some(card=>(card.effects||[]).some(effect=>effect.timing==='trigger'));if(canReturn){footer.classList.add('counter-footer-three');footer.prepend(el('button',{class:'counter-back-button',onClick:()=>this.leaderRedirect(g)},'戻る'))}
};
