import{UI}from'./ui-fixed.js?v=3122';
const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null&&value!==undefined)node.setAttribute(key,value)}for(const child of children.flat())node.append(child?.nodeType?child:document.createTextNode(child??''));return node};
UI.prototype.showLife=function(side,g){
 this.close();document.body.classList.remove('hand-open');const sideState=g.sides[side],cards=[...sideState.life].reverse(),revealed=new Set(cards.filter(card=>card.faceUp).map(card=>card.uid)),selected=new Set();
 const overlay=el('div',{class:'dialog'}),panel=el('section',{class:'sheet life-image-sheet'}),status=el('p'),grid=el('div',{class:'life-image-grid'});
 const update=()=>{status.textContent=`ライフ：${sideState.life.length}枚 / ${selected.size}枚選択`;grid.replaceChildren();cards.forEach((card,index)=>{const open=revealed.has(card.uid),wrap=el('div',{class:`life-image-wrap ${selected.has(card.uid)?'selected':''}`}),face=el('button',{class:`life-image-card ${open?'front':'back'}`});if(open){face.append(card.imageUrl?el('img',{src:card.imageUrl,alt:card.name,loading:'lazy'}):el('div',{class:'life-image-fallback'},card.name),el('span',{class:'life-position'},`上から${index+1}枚目`),el('strong',{},card.name))}else face.append(el('div',{class:'life-card-back'},el('b',{},'LIFE'),el('span',{},`上から${index+1}枚目`)));face.addEventListener('click',()=>{if(open){revealed.delete(card.uid);selected.delete(card.uid)}else revealed.add(card.uid);update()});const pick=el('button',{class:`life-image-select ${selected.has(card.uid)?'selected':''}`,disabled:open?null:'disabled',onClick:()=>{selected.has(card.uid)?selected.delete(card.uid):selected.add(card.uid);update()}},selected.has(card.uid)?'✓ 選択中':'選択');wrap.append(face,pick);grid.append(wrap)})};
 const move=(label,to)=>el('button',{onClick:()=>selected.size&&this.a.bulkMove(side,'life',to,[...selected])},label);
 panel.append(el('h2',{},`${side==='player'?'自分':'AI'}のライフ`),status,el('p',{class:'zone-help'},'裏向きカードをタップすると、カード画像を確認できます。'),el('div',{class:'flip-tools'},el('button',{onClick:()=>{cards.forEach(card=>revealed.add(card.uid));update()}},'すべて表向き'),el('button',{onClick:()=>{revealed.clear();selected.clear();update()}},'すべて裏向き')),grid,el('div',{class:'zone-actions'},move('手札へ','hand'),move('トラッシュへ','trash'),move('デッキ上へ','deckTop'),move('デッキ下へ','deckBottom'),move('ライフ上へ','lifeTop'),move('場へ','field')),el('button',{onClick:()=>selected.size===1&&this.a.useTrigger(side,[...selected][0])},'選択カードのトリガーを使用'),el('button',{class:'primary zone-close',onClick:()=>this.close()},'閉じる'));
 overlay.append(panel);this.modal=overlay;document.body.append(overlay);update();
};
