import{GameEngine}from'./game-engine-v3.js?v=3430';import{UI}from'./ui-fixed.js?v=3430';
const el=(tag,attrs={},...children)=>{const node=document.createElement(tag);for(const[key,value]of Object.entries(attrs)){if(key==='class')node.className=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2).toLowerCase(),value);else if(value!==null&&value!==undefined)node.setAttribute(key,value)}for(const child of children.flat())node.append(child?.nodeType?child:document.createTextNode(child??''));return node};
const normalizeDarkWater=card=>{if(card?.id!=='OP16-115')return card;card.cost=1;card.counter=0;card.traits=['王下七武海','黒ひげ海賊団'];card.text='【メイン】自分のリーダーが特徴《黒ひげ海賊団》を持つ場合、自分のトラッシュから「闇水」以外の【トリガー】を持つカード1枚までを、手札に加える。【トリガー】相手のリーダーかキャラ1枚までを、このターン中、効果を無効にする。';card.effects=[{timing:'onPlay',action:'darkWaterMainChoice'},{timing:'trigger',action:'darkWaterNegateChoice'}];return card};
const normalizeState=state=>{if(!state)return;for(const side of['player','ai']){const s=state.sides[side];for(const card of [s.leader,...s.deck,...s.hand,...s.life,...s.field,...s.trash,s.stage].filter(Boolean))normalizeDarkWater(card)}};
const previousTrigger=GameEngine.prototype.resolveTrigger;GameEngine.prototype.resolveTrigger=function(use){normalizeDarkWater(this.state.pending?.card);return previousTrigger.call(this,use)};const previousUseTrigger=GameEngine.prototype.useTrigger;GameEngine.prototype.useTrigger=function(side,id){normalizeDarkWater(this.state.sides[side].life.find(card=>card.uid===id));return previousUseTrigger.call(this,side,id)};
const previousEndBattle=GameEngine.prototype.endBattle;GameEngine.prototype.endBattle=function(){if(['darkWaterMainChoice','darkWaterNegateChoice'].includes(this.state.pending?.kind))return true;return previousEndBattle.call(this)};
GameEngine.prototype.resolveDarkWaterChoice=function(side,targetUid=null){const pending=this.state.pending;if(!['darkWaterMainChoice','darkWaterNegateChoice'].includes(pending?.kind)||pending.side!==side)return false;if(pending.kind==='darkWaterMainChoice'){const own=this.state.sides[side],target=own.trash.find(card=>card.uid===targetUid&&pending.options.includes(card.uid));if(target){own.trash=own.trash.filter(card=>card.uid!==target.uid);own.hand.push(target);this.log(target.name+'をトラッシュから手札に加えた')}else this.log('回収するカードを選ばなかった')}else{const foe=this.state.sides[pending.targetSide],target=targetUid===foe.leader.uid?foe.leader:foe.field.find(card=>card.uid===targetUid);if(target&&pending.options.includes(target.uid)){target.effectsNegatedThroughTurn=this.state.turn;this.log(target.name+'の効果をこのターン中無効にした')}else this.log('効果を無効にする対象を選ばなかった')}this.state.pending=null;this.state.phase='main';this.syncBurgessPower?.();return true};
const previousRender=UI.prototype.renderGame;UI.prototype.renderGame=function(g){normalizeState(g);previousRender.call(this,g);if(g.pending?.kind==='darkWaterMainChoice'&&g.pending.side==='player')this.darkWaterPicker(g,false);if(g.pending?.kind==='darkWaterNegateChoice'&&g.pending.side==='player')this.darkWaterPicker(g,true)};
UI.prototype.darkWaterPicker=function(g,negate){this.close();const pending=g.pending,sideState=negate?g.sides[pending.targetSide]:g.sides.player,cards=pending.options.map(id=>negate&&id===sideState.leader.uid?sideState.leader:(negate?sideState.field:sideState.trash).find(card=>card.uid===id)).filter(Boolean),overlay=el('div',{class:'dialog'}),panel=el('section',{class:'sheet effect-picker'}),grid=el('div',{class:'effect-target-grid'});for(const card of cards){const button=el('button',{},card.imageUrl?el('img',{src:card.imageUrl,alt:card.name}):'',el('strong',{},card.name),el('small',{},card.id+'　C'+(card.cost??'-')));button.addEventListener('click',()=>this.a.darkWaterChoice(card.uid));grid.append(button)}panel.append(el('h2',{},negate?'闇水：効果を無効':'闇水：カード回収'),el('p',{},negate?'効果をこのターン中無効にする相手リーダーかキャラを1枚まで選びます。':'トラッシュから「闇水」以外のトリガーカードを1枚まで手札に加えます。'),cards.length?grid:el('p',{class:'empty-choice'},'選択できるカードがありません'),el('button',{onClick:()=>this.a.darkWaterChoice(null)},'選ばず終了'));overlay.append(panel);this.modal=overlay;document.body.append(overlay)};
